development:
  adapter: postgresql
  encoding: unicode
  database: heroku-connect-rails
  pool: 5
  username: postgres
  password: moomoo58




default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5